name: Deploy Application

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy via SSH
    runs-on: ubuntu-latest
    environment: 
      name: prod
      url: https://tercovirtual.gabriel2m.com

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Application
        run: |
          echo ${{ secrets.SSH_PRIVATE_KEY }} | ssh -o StrictHostKeyChecking=no -i /dev/stdin -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd ${{ secrets.APP_PATH }}
            git pull
            php composer install --no-dev --optimize-autoloader
            php artisan optimize
          EOF
